For this lab, you will be using the CSV files provided in the files_for_lab folder. These are cleaned versions of the learningSet data from the Case Study 'Healthcare for All'.

Instructions: 

- Apply the Random Forests algorithm but this time only by upscaling the data.

- Use Feature Selections that you have learned in class to decide if you want to use all of the features (PCA, etc)

- Discuss the output and its impact in the bussiness scenario. Is the cost of a false positive equals to the cost of the false negative? How would you change your algorithm or data in order to maximize the return of the bussiness?

In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')

In [2]:
numerical=pd.read_csv('numerical.csv')
categorical=pd.read_csv('categorical.csv')
targets=pd.read_csv('target.csv')

## 1) Apply the Random Forests algorithm but this time only by upscaling the data. 

In [5]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

data = pd.concat([numerical, categorical, targets], axis = 1)
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

In [6]:
data.isna().sum().sum()

0

In [7]:
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis = 1)

numericalX = X.select_dtypes(np.number)
categoricalX = X.select_dtypes(np.object)

# we OneHotEncode the categoricals so we can use the same dataset to perform a regression later (in the lab).
# it is not needed for a DecisionTree or RandomForest model
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(categoricalX)
encoded_categorical = encoder.transform(categoricalX).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical)
X = pd.concat([numericalX, encoded_categorical], axis = 1)

# Note: we need to do train/test split before downsampling, and then only downsample the training set - Why?
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
from sklearn.utils import resample

# for upsampling we need to temporarily concat X_train and y_train
trainset = pd.concat([X_train, y_train], axis=1)

# quicker way to upsample category 1:

category_0 = trainset[trainset['TARGET_B']== 0 ]
category_1_upsampled = resample(trainset[trainset['TARGET_B']==1], replace=True, n_samples = len(category_0))


trainset_new = pd.concat([category_0, category_1_upsampled], axis = 0)
trainset_new = trainset_new.sample(frac =1) #randomize the rows
X_train = trainset_new.drop(['TARGET_B'], axis=1)
y_train = trainset_new['TARGET_B']
#data = data.reset_index(drop=True)
print(X_train.shape)

(144972, 355)


In [9]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']

# Now we can remove the column target d from the set of features
X_train = X_train.drop(['TARGET_D'], axis = 1)
X_test = X_test.drop(['TARGET_D'], axis = 1)

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, min_samples_split=20, min_samples_leaf =20, max_samples=0.2,random_state = 42)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

y_pred = clf.predict(X_test)
display(y_test.value_counts())
display(confusion_matrix(y_test, y_pred))

0.6236997489170323
0.5897919614316407


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[10696,  7387],
       [  441,   559]], dtype=int64)

## Use Feature Selections that you have learned in class to decide if you want to use all of the features (PCA, etc)

### 1) Feature Selection using K Best: Used already on Wednesday Lab therefore would go for different !!
#### Only writing the steps !!

In [ ]:
# we will use MinMaxScaler for this
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
numerical_scaled = scaler.fit_transform(numerical)

In [ ]:
X = numerical_scaled
y = target['TARGET_B']

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
kbest = SelectKBest(chi2, k=10).fit_transform(X, y)
# Here we choose 10 so that is easier to analyze results later, as we will see
selected = pd.DataFrame(kbest)
selected.head()

In [ ]:
# To check the scores
model = SelectKBest(chi2, k=10).fit(X, y)
df = pd.DataFrame(data = model.scores_, columns = ['score'])
df['Column'] = numerical.columns
print(df.sort_values(by = ['score'], ascending = False).head(10))

In [ ]:
cols = df.sort_values(by = ['score'], ascending = False).head(10)['Column']
cols

In [ ]:
selected.columns = cols
selected.head()

In [ ]:
donors = pd.concat([selected, categorical, target], axis=1)
donors

### 2) Recursive Feature Elimination
##### Only writing the steps !!

In [ ]:
X = numerical_scaled
y = targets['TARGET_D']

from sklearn.feature_selection import RFE
from sklearn import linear_model
lm = linear_model.LinearRegression()
rfe = RFE(lm, n_features_to_select=20, verbose=False)
rfe.fit(X, y)

In [ ]:
df2 = pd.DataFrame(data={'Column': numerical.columns,'Ranking': rfe.ranking_} )
df2.head()

In [ ]:
# After we run the algorithm, it labels the top features as 1 and the rest are marked in an increasing order of importance.
df = pd.DataFrame(data = rfe.ranking_, columns=['Rank'])
df['Column_name'] = pd.DataFrame(numerical).columns
df[df['Rank']<11]
#df['Rank'].value_counts()

## PCA - Principal Component Analysis

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
scaler = StandardScaler()
#scaler.fit(X_train)
#X_train_scaled = scaler.transform(X_train)
#same thing in 1 line
X_train_scaled = scaler.fit_transform(X_train)

In [11]:
X_test_scaled = scaler.transform(X_test)

In [14]:
from sklearn.decomposition import PCA

In [15]:
pca = PCA(0.90)
pca.fit(X_train_scaled)

PCA(n_components=0.9)

In [16]:
pca.explained_variance_ratio_

array([0.11745628, 0.08770275, 0.07221561, 0.03914188, 0.03568083,
       0.02730114, 0.0225066 , 0.02089261, 0.01894096, 0.01719657,
       0.01325714, 0.01223543, 0.01131993, 0.01047225, 0.01018715,
       0.00999825, 0.00946273, 0.00875642, 0.00834929, 0.0080928 ,
       0.00762756, 0.00716111, 0.00692991, 0.00658901, 0.00624533,
       0.00596209, 0.00550632, 0.00536359, 0.00523727, 0.00514022,
       0.00510738, 0.00486138, 0.00479492, 0.00465645, 0.00457095,
       0.00448988, 0.00442626, 0.00433231, 0.004279  , 0.00421023,
       0.004146  , 0.00405051, 0.00397396, 0.00393703, 0.0039106 ,
       0.00383419, 0.00374189, 0.00370734, 0.00366294, 0.00359345,
       0.00353545, 0.00342365, 0.00339629, 0.00333324, 0.00326642,
       0.00325456, 0.00323784, 0.00320835, 0.00317515, 0.00309926,
       0.00305887, 0.00303434, 0.00299023, 0.00297024, 0.00294262,
       0.00291292, 0.00289165, 0.00285728, 0.0028549 , 0.00281458,
       0.00280639, 0.00277575, 0.00275813, 0.002751  , 0.00269

In [17]:
X_train_pca = pca.transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, min_samples_split=20, min_samples_leaf =20, max_samples=0.2,random_state = 42)
clf.fit(X_train_pca, y_train)
print(clf.score(X_train_pca, y_train))
print(clf.score(X_test_pca, y_test))

y_pred = clf.predict(X_test_pca)
display(y_test.value_counts())
display(confusion_matrix(y_test, y_pred))

0.6551885881411583
0.673950636692344


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[12434,  5649],
       [  573,   427]], dtype=int64)

In [ ]:
# After PCA ==> Random Forest
# 12434 nr. prediction was that there is no donation, & in actual it was also the same. 
# 5649 nr. prediction that there was donation & in actuality it was not

# Before PCA ==> Random Forest
# 10696 nr. prediction was that there is no donation, & in actual it was also the same. 
# 7387 nr. prediction that there was donation & in actuality it was not


# After PCA, results are improved when compared to without PCA !!

In [ ]:
# without PCA
0.6236997489170323
0.5897919614316407
0    18083
1     1000
Name: TARGET_B, dtype: int64
array([[10696,  7387],
       [  441,   559]], dtype=int64)

In [ ]:
# predicted | 0 | 1 | 
# --------------------------
# actual  0 | + |  | 
# --------------------------
#         1 |   | +

### 3) Discuss the output and its impact in the bussiness scenario.

#### Is the cost of a false positive equals to the cost of the false negative? How would you change your algorithm            or data in order to maximize the return of the bussiness?

# Lab | Final regression model in "Health Care for All" Case

## Instructions
#### 1) At this point, we have created a model to predict who will make a donation and who won't. But, what about the ammount of money that each person will give? In this lab, subset those that made a donation and use that subset to create a model to predict how much money will they give.



In [20]:
data1 = pd.concat([numerical, categorical, targets], axis = 1)
data1['TARGET_D'].value_counts()

0.00     90569
10.00      941
15.00      591
20.00      577
5.00       503
         ...  
18.25        1
10.70        1
2.50         1
16.87        1
44.21        1
Name: TARGET_D, Length: 71, dtype: int64

In [21]:
data_d= data1[data1['TARGET_B']==1]

In [22]:
data_d

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
20         2  62.000000       3        8   10         2       25        40   
30         0  61.611649       5        9    0         1       37        58   
45         0  66.000000       5        9    5         0       33        24   
78         0  69.000000       6        9    0         0       34        20   
93         1  73.000000       1        7   10         0       21        53   
...      ...        ...     ...      ...  ...       ...      ...       ...   
95298      2  45.000000       5        9    0         0       45        28   
95309      0  51.000000       5        6    1         1       32        43   
95398      0  86.000000       5        9    0         1       32        21   
95403      0  58.000000       4        9    0         0       24        46   
95410      0  58.000000       7        9    0         0       28        35   

       WWIIVETS  LOCALGOV  STATEGOV  FEDGOV  WEALTH2  POP901  POP902  POP903  \
20           27        11         4       1        9    2707     672     929   
30           16         8         1       5        9    2147     591     640   
45           39         6         5       1        9    2160     683     900   
78           54         2         3       1        9   13801    3736    6388   
93            8         5         4      11        7    1673     418     462   
...         ...       ...       ...     ...      ...     ...     ...     ...   
95298        37         9         2       3        2    2649     671    1098   
95309        24         7         5       6        6    8361    2324    3112   
95398        26         9         1       0        9    2368     651     930   
95403        20         6         1       2        5    1663     450     581   
95410        20         9         1       1        7    1746     432     508   

       POP90C1  POP90C2  POP90C3  POP90C4  POP90C5  ETH1  ETH2  ETH3  ETH4  \
20          99        0        0       45       55    97     1     0     2   
30          99        0        0       49       51    94     2     0     3   
45          89        0       11       48       52    99     0     0     1   
78          99        0        0       48       52    97     0     0     3   
93          99        0        0       49       51     7    93     0     0   
...        ...      ...      ...      ...      ...   ...   ...   ...   ...   
95298        0       99        1       46       54    94     1     1     1   
95309       99        0        0       50       50    90     1     1     7   
95398       99        0        0       50       50    85    12     0     3   
95403        0        1       99       50       50    99     0     0     0   
95410       99        0        0       47       53    92     1     1     5   

       ETH5  ETH6  ETH7  ETH8  ETH9  ETH10  ETH11  ETH12  ETH13  ETH14  ETH15  \
20        1     0     0     0     0      1      0      0      1      0      0   
30        5     1     0     1     1      0      0      0      3      0      0   
45        1     0     0     0     0      0      0      0      0      0      0   
78        3     0     1     1     0      0      0      0      2      0      0   
93        0     0     0     0     0      0      0      0      0      0      0   
...     ...   ...   ...   ...   ...    ...    ...    ...    ...    ...    ...   
95298     8     0     0     0     0      0      0      0      6      0      0   
95309     9     1     1     1     3      0      0      0      6      0      0   
95398     1     1     0     1     1      0      0      0      1      0      0   
95403     0     0     0     0     0      0      0      0      0      0      0   
95410     8     0     1     2     0      1      0      0      5      0      0   

       ETH16  AGE901  AGE902  AGE903  AGE904  AGE905  AGE906  AGE907  CHIL1  \
20         0      35      42      43      37      47      50      27     34   
30         2      29      36      37     

In [103]:
data_d['TARGET_D'].info

<bound method Series.info of 20        4.0
30        7.0
45        5.0
78       13.0
93       10.0
         ... 
95298    20.0
95309    15.0
95398     3.0
95403    10.0
95410    18.0
Name: TARGET_D, Length: 4843, dtype: float64>

In [86]:
y= data_d ['TARGET_D']
X= data_d.drop(['TARGET_B', 'TARGET_D'], axis = 1)

In [87]:
y.shape

(4843,)

In [88]:
X.shape

(4843, 337)

In [89]:
X = pd.DataFrame(X)
X.shape

(4843, 337)

In [90]:
X_numerical = X.select_dtypes(np.number)
X_categorical = X.select_dtypes(np.object)

# X_categorical.shape
X_numerical.shape

(4843, 330)

In [92]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(X_categorical)
encoded_categorical = encoder.transform(X_categorical).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical)
# encoded_categorical.shape
encoded_categorical = encoded_categorical.reset_index(drop=True)
X_numerical = X_numerical.reset_index(drop=True)
X_concat = pd.concat([X_numerical, encoded_categorical], axis = 1)
X_concat.shape

(4843, 354)

In [110]:
model1 = DecisionTreeRegressor()
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()
from sklearn.neighbors import KNeighborsRegressor
model3 = KNeighborsRegressor()
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import numpy as np

scaler = StandardScaler()
X = scaler.fit_transform(X_concat)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)


model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=5))
    scores[model_name] = mean_score
print(scores)

# We can use the result to choose the best performing model

{'Decision Tree Regressor': -0.062380326806291554, 'Linear Regression': 0.26404664726574784, 'KNN': 0.05137267026692192}


In [109]:
from sklearn import neighbors
clf = neighbors.KNeighborsRegressor(n_neighbors=7, weights='uniform')
clf.fit(X_train, y_train)
predictions_clf = clf.predict(X_val)
clf.score(X_val, y_val)

0.16412563993815044

#### 2) Evaluate the result of your model and estimate how much better the result are for the bussiness in comparison with the naive scenario we discuss on Monday.